{
  "name": "fn-retry",
  "version": "1.0.7",
  "description": "Retry failed function call",
  "main": "./dist/index.js",
  "directories": {
    "test": "jest"
  },
  "scripts": {
    "start": "webpack --watch --config ./config/webpack.config.js",
    "build:prod": "webpack --mode production --config ./config/webpack.config.js",
    "build:dev": "webpack --mode development --config ./config/webpack.config.js",
    "test": "jest",
    "examples": "node ./example/run-examples.js",
    "prepublishOnly": "npm run build:prod"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/vadimkorr/fn-retry.git"
  },
  "keywords": [
    "js",
    "javascript",
    "promise",
    "async",
    "await"
  ],
  "author": "Vadim Kor",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/vadimkorr/fn-retry/issues"
  },
  "homepage": "https://github.com/vadimkorr/fn-retry#readme",
  "devDependencies": {
    "@babel/core": "^7.10.5",
    "@babel/plugin-transform-runtime": "^7.10.5",
    "@babel/preset-env": "^7.10.4",
    "babel-jest": "^26.1.0",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "eslint": "^7.5.0",
    "jest": "^26.1.0",
    "node-fetch": "^3.1.1"
  }
}